version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: 'yes'
    extra_hosts:
        - host.docker.internal:${HOST_IP:-172.17.0.1}
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./environment/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    volumes:
        - ./environment/mysql/my.cnf:/etc/mysql/my.cnf
        - ./environment/docker-runtime/mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  pma:
      image: phpmyadmin
      ports:
          - 8080:80
      environment:
          PMA_HOST: db
          PMA_USER: ${DB_USERNAME}
          PMA_PASSWORD: ${DB_PASSWORD}
          PHP_UPLOAD_MAX_FILESIZE: 1G
          PHP_MAX_INPUT_VARS: 1G
      networks:
          - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
